#preload=$HOME/Pictures/wallpapers/wp6374897.webp
#wallpaper=,$HOME/Pictures/wallpapers/wp6374897.webp

#preload=$HOME/Pictures/wallpapers/Lofi-Cafe1.png
#wallpaper=,$HOME/Pictures/wallpapers/Lofi-Cafe1.png

wallpaper {
	monitor =
	path = $HOME/Pictures/wallpapers/Lofi-Cafe1.png
}
